description = "Ubuntu 22.04 Jammy Jellyfish full image with buildpacks for Java, Go, Python, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:4.0.0"
  version = "4.0.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:0.28.0"
  version = "0.28.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php:2.0.0"
  version = "2.0.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.5.0"
  version = "5.5.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/python:2.7.0"
  version = "2.7.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ruby:0.21.0"
  version = "0.21.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/web-servers:0.4.0"
  version = "0.4.0"

[lifecycle]
  version = "0.15.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ruby"
    version = "0.21.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "4.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.7.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php"
    version = "2.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "0.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "0.28.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.5.0"

[stack]
  build-image = "registry.gitlab.com/var-app/code/build-jammy-varapp:latest"
  id = "io.buildpacks.stacks.jammy"
  run-image = "registry.gitlab.com/var-app/code/run-jammy-varapp"
  run-image-mirrors = []
